--- 
codes: 
 app: WORKFLOW
 modulo: OPERACIONES
cookieAplicativa: 
 nombre: token
 response: Response
bitacora:
 aplicacion: WFOperaciones
 idInstWeb: workflow-oper-web-mx-operaciones-wf-dev.appls.cto1.paas.gsnetcloud.corp
front: 
 title: WorkFlow Operaciones
 fileNetConsulta: SessionFactoryFnTempWFO
 maxFileSizeFront: 15
 url: 
  sesion: 
   actualizar: api/tallerproductos/sessiones/actualizar
   consultar: api/tallerproductos/sessiones/consultar
   eliminar: api/tallerproductos/sessiones/eliminar
  uri: 
   validar: "http://url.uri.validar"
 sal:
  errores:
   polban000003: "Usuario no encontrado en la portalización."
   polban000002: "El usuario no se ha firmado en el portal."
   polban000001: "Error inesperado al consumir el servicio SAL."
 config:
  errores:
   tokenNoinformado: "Cookie/Token no informado."
spring:
 datasource:
  hikari:
   connection-timeout: 20000
   minimum-idle: 10
   maximum-pool-size: 10
   idle-timeout: 10000
 rabbitmq:
  listener:
   simple:
    default-requeue-rejected: false
    retry:
     enabled: false
  cache:
   connection:
    mode: CONNECTION
    size: 10 
  host: 192.168.10.105
  port: 15672
  username: guest
  password: guest
  queue: Q.WFOPERACIONES_PISTAS_AUDITORIA_D
  queueadmin: fdfd
 jackson:
  date-format: MM/dd/yyyy HH:mm a Z
  time-zone: America/Mexico_City
 profiles:
  active: dev, pre
 jpa:
   show-sql: true
   generate-ddl: false
   properties:
    hibernate:
     proc:
      param_null_passing: true
     dialect: org.hibernate.dialect.Oracle12cDialect
     ddl-auto: validate
     hbm2ddl:
      import_files:
 cloud:
  config:
   failFast: true
   retry:
   #Intervalo de tiempo inicial entre cada repeticion
    initialInterval: 6000
   #Incremento exponencial del tiempo de intervalo inicial
    multiplier: 1.5
   #Tiempo maximo al que puede crecer el intervalo
    maxInterval: 30000
 redis:
  host: 192.168.10.106
  port: 6379 
  password:
api-invoker-lib:
 app-name: ${spring.application.name}
 token:
  url: https://front-grants-bussupport-comsrvc-security-appint-dev.appls.cto1.paas.gsnetcloud.corp/oauth2/v1/token
  urlB412: https://webapigateway.dev.mx.corp/santander-mexico/factorias/current-account-inquiry/v1.1.0/operationsAndExecution/productSpecificFulfilment/loansAndDeposits/currentAccount/currentAccountInq/accounts 
  urlPE68: https://webapigateway.dev.mx.corp/santander-mexico/factorias/party-data-inquiry/v1.1.0/referenceData/party/partyDataManagement/partyDataInq/parties
  scopes: current-account-inquiry_1.1.0 party-data-inquiry_1.1.0
  grantType: client_credentials
  clientIdParty: cZMAZCqron9RumO27s1tisBAOazx077rwlIoSHSwrJY
  clientSecretParty: JCi80QDA0cCEp6Tsr9ofqs5UEJZFwoqUD5YSm-El2Sk
  clientIdAcc: GtVjqOa2kYytQZI25eJbNgxndT9ZAJl_kRtz7Py5JPU
  globalId: 1111000111088
logging:
 level:
  org:
   hibernate: TRACE
   springframework:
    orm:
     jpa: TRACE
  com:
   zaxxer:
    hikari: TRACE
log4j:
 logger:
  com.zaxxer.hikari: TRACE
servicios:
 configsftp:
  identitySFTP: /home/detrwfop/ssh/id_rsa
  knownHostSFTP: /home/detrwfop/ssh/known_hosts
  userSFTP: detrwfop
  passSFTP: detrwfop
  ipSFTP: 192.168.10.106
  portSFTP: 22
 authentication:
  userTata: sriram.natarajan1@tcs.com
  passTata: WeGotThis@234
  userVass: wf_apiRequestor
  passVass: Wfapi12345
  userSantander: samyuktha.salivendra@tcs.com
  passSantander: Puppybindu@00
 urls:
  urlsWebApiTata: https://tcs-santander.appiancloud.com/suite/
  urlsWebApiVass: https://vassmx.appiancloud.com/suite/
  urlsWebApiSantander: https://tcs-santander.appiancloud.com/suite/
  urlMsFoliador: http://localhost:8085/foliador/gen_folio
  urlMsSolicitudes: http://localhost:8084
  urlMsAdmin: http://localhost:9885
  urlMsCargaDesc: http://localhost:9888
  urlMsDetalle: http://192.168.10.105:9887
  urlMsTransacciones: http://localhost:9887/detalles/transaciones/
  urlCargaDescarga: https://cargadescarga-service-mx-operaciones-wf-dev.appls.cto1.paas.gsnetcloud.corp/cargas_descargas/documentos/descargas_transferencias_seguras_datos_archivos
  endpointMSIAppian: http://localhost:9887/detalles/meses_sin_intereses
  urlOpenText: https://srvccedvlmx03.dev.mx.corp:1443/contract-service/ContractService
filenet:
 urls:
  urlMsTransversalSave: https://light-gateway-gd-mx-aperturabei-destdoc-dev.appls.cto1.paas.gsnetcloud.corp/stgd/archivos
  urlMsTransversal: https://light-gateway-gd-mx-aperturabei-destdoc-dev.appls.cto1.paas.gsnetcloud.corp/stgd/documentos
  urlMsGateway: https://light-gateway-gd-mx-aperturabei-destdoc-dev.appls.cto1.paas.gsnetcloud.corp:443/token
  #urlMsTransversal: https://light-gateway-gd-mx-aperturabei-destdoc-dev.appls.cto1.paas.gsnetcloud.corp/stgd/documentos
  #urlMsGateway: https://light-gateway-gd-mx-aperturabei-destdoc-dev.appls.cto1.paas.gsnetcloud.corp/token
 authentication:
  idCliente: 0f050766-f4e3-4583-b75c-3ec4b90a5335
commons:
 email:
  urlEmail: https://wscetdlm1mxr201.dev.mx.corp:1443/WarWSCommonEmail/WSCommonEmailEndPoint
oracle:
 datasource:
  bdadmin:
   adminUrl: jdbc:oracle:thin:@192.168.10.106:1560/odmxwfop
   adminUsername: DEIFADMN
   adminPassword: DEIFADMN
   adminDriverClassName: oracle.jdbc.OracleDriver
   adminValidation-query: SELECT 1 FROM dual
  bdclient:
   clientUrl: jdbc:oracle:thin:@192.168.10.106:1560/odmxwfop
#   clientUrl: jdbc:oracle:thin:@192.168.10.105:16602/odmxwfo1
   clientUsername: DEIFCLNT
   clientPassword: DEIFCLNT
#   clientPassword: L1sNl#6zM4l
   clientDriverClassName: oracle.jdbc.OracleDriver
   clientValidation-query: SELECT 1 FROM dual
  bdprocesos:
   procesosUrl: jdbc:oracle:thin:@192.168.10.106:1560/odmxwfop
#   procesosUrl: jdbc:oracle:thin:@192.168.10.105:16601/odmxwfo3
#   procesosUsername: DEIFPREX
#   procesosPassword: X8kn4Z#iLO
   procesosUsername: DEIFPREX
   procesosPassword: DEIFPREX
   procesosDriverClassName: oracle.jdbc.OracleDriver
   procesosValidation-query: SELECT 1 FROM dual
  bdoperativa:
   operativaUrl: jdbc:oracle:thin:@192.168.10.106:1760/odmxappn
#   operativaUrl: jdbc:oracle:thin:@192.168.10.105:16600/odmxwfo2
#   operativaUsername: DEIFOPER
#   operativaPassword: P4gS#6Tr4nsF
   operativaUsername: DEHTOPER
   operativaPassword: DEHTOPER
   operativaDriverclassName: oracle.jdbc.OracleDriver
   operativaDalidation-query: SELECT 1 FROM dual
  bdpistas:
   pistasUrl: jdbc:oracle:thin:@192.168.10.106:1560/odmxwfop
   pistasUsername: DEHTPIST
   pistasPassword: pistPass
   pistasDriverClassName: oracle.jdbc.OracleDriver
   pistasDalidation-query: SELECT 1 FROM dual
   pool:
    operacionesMaximumPoolSize: 30
    operacionesConnectionTimeout: 30000
    operacionesidleTimeout: 30000
    operacionesMinimumIdle: 5
    operacionesLeakDetectionThreshold: 40000
reportes:
 queries:
  appianQuery: SELECT sol.TXT_COMEN, sol.VAL_DIV, sol.VAL_FOLIO, sol.USR_SOLIC, sol.DSC_SOLIC, sol.USR_VALID, sol.DSC_VALID, sol.USR_APROB, sol.DSC_APROB, sol.VAL_REGION, sol.VAL_ZONA FROM SIO_MX_MAE_APPN_SOL_DRO sol